# -*- mode: ruby -*-
# vi: set ft=ruby :

# Created by Ricardo Schmidt - ricardo.xmit@gmail.com

VAGRANTFILE_API_VERSION = "2"

# Feel free to add new parameters
nodes = [
  { :name => :webserver, :role => 'nginx',    :type => 'm3.medium'},
  { :name => :memcache,  :role => 'memcache', :type => 'm1.large'}
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  nodes.each do |opts|
    config.vm.define opts[:name] do |awsx|
      # You have to 'vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'
      awsx.vm.box = "dummy"

      awsx.vm.provider :aws do |aws, override|
        aws.access_key_id = ""
        aws.secret_access_key = ""
        aws.keypair_name = ""
        aws.security_groups = ['ssh']
        aws.region = "ap-southeast-2"
        aws.instance_type = opts[:type]

        # debian wheezy box
        aws.ami = "ami-ed264bd7"

        # it has to be admin user to ssh
        override.ssh.username = "admin"
        
        # where your key is located?
        override.ssh.private_key_path = "/Users/ricardo/.ssh/id_rsa"
      end

      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/Users/ricardo/Desktop/vagrant-xmit/aws/playbook/" + opts[:role] +".yml"
        #ansible.vault_password_file = ANSIBLE_VAULT
        ansible.verbose = "vvvv"
        ansible.host_key_checking = "false"
      end

      #config.vm.share_folder  "stuff", "/usr/local/stuff", "/bla/stuff", :nfs => true if opts[:shares]
      # nfs is much faster than VirtualBox shared files. Use it!

    end  
  end

end
